package main

import (
	_ "go-backend-api/cmd/swag/docs"
	"go-backend-api/internal/initialize"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware
	// docs is generated by Swag CLI, you have to import it.
)

// @title           API DOCUMENTATION PARKING BACKEND
// @version         1.0.0
// @description     This is a sample server celler server.
// @termsOfService  github.com/phananhtu1998/go-backend-api

// @contact.name   TEAM AI
// @contact.url    github.com/phananhtu1998/go-backend-api
// @contact.email  teamaithacoindustries@gmail.com

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath  /v1/2025
// @schemas    http

// @securityDefinitions.apikey BearerAuth
// @type apiKey
// @in header
// @name Authorization
// @description Nhập Bearer Token vào header. Ví dụ: "Bearer {token}"

// @securityDefinitions.apikey ApiKeyAuth
// @type apiKey
// @in header
// @name X-API-Key
// @description Nhập API Key vào header để xác thực API

// @securityDefinitions.apikey TokenKey
// @type apiKey
// @in header
// @name TokenKey
// @description Nhập Token Key vào header để xác thực API

// @security [BearerAuth, ApiKeyAuth, TokenKey]

func main() {
	r := initialize.Run()
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, ginSwagger.PersistAuthorization(true)))
	r.Run(":8002")
}
