// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 0004_role.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const countAllFuncPackageByCreatedBy = `-- name: CountAllFuncPackageByCreatedBy :one
SELECT COUNT(r.id) AS total
FROM role r
LEFT JOIN license l ON r.id = l.role_id AND l.is_deleted = false
WHERE r.is_deleted = false
  AND r.created_by = ?
  AND (
    ? IS NULL OR
    r.code LIKE CONCAT('%', ?, '%') OR
    r.role_name LIKE CONCAT('%', ?, '%') OR
    EXISTS (
        SELECT 1 FROM role_account ra
        JOIN account a ON a.id = ra.account_id
        WHERE ra.role_id = r.id AND ra.is_deleted = false AND a.is_deleted = false
        AND (
            a.username LIKE CONCAT('%', ?, '%') OR
            a.name LIKE CONCAT('%', ?, '%')
        )
    ) OR
    EXISTS (
        SELECT 1 FROM roles_menu rm
        JOIN menu m ON m.id = rm.menu_id
        WHERE rm.role_id = r.id AND rm.is_deleted = false AND m.is_deleted = false
        AND m.menu_name LIKE CONCAT('%', ?, '%')
    )
  )
`

type CountAllFuncPackageByCreatedByParams struct {
	CreatedBy string
	Column2   interface{}
	CONCAT    interface{}
	CONCAT_2  interface{}
	CONCAT_3  interface{}
	CONCAT_4  interface{}
	CONCAT_5  interface{}
}

func (q *Queries) CountAllFuncPackageByCreatedBy(ctx context.Context, arg CountAllFuncPackageByCreatedByParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllFuncPackageByCreatedBy,
		arg.CreatedBy,
		arg.Column2,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.CONCAT_3,
		arg.CONCAT_4,
		arg.CONCAT_5,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createRole = `-- name: CreateRole :execresult
INSERT INTO ` + "`" + `role` + "`" + ` (
  id, code, role_name, role_left_value, role_right_value,license_id,
  role_max_number, created_by, create_at, update_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW()
)
`

type CreateRoleParams struct {
	ID             string
	Code           string
	RoleName       string
	RoleLeftValue  int32
	RoleRightValue int32
	LicenseID      string
	RoleMaxNumber  int32
	CreatedBy      string
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.Code,
		arg.RoleName,
		arg.RoleLeftValue,
		arg.RoleRightValue,
		arg.LicenseID,
		arg.RoleMaxNumber,
		arg.CreatedBy,
	)
}

const decreaseLeftValues = `-- name: DecreaseLeftValues :exec
UPDATE role
SET role_left_value = role_left_value - ?
WHERE role_left_value > ? AND is_deleted = false
`

type DecreaseLeftValuesParams struct {
	RoleLeftValue   int32
	RoleLeftValue_2 int32
}

func (q *Queries) DecreaseLeftValues(ctx context.Context, arg DecreaseLeftValuesParams) error {
	_, err := q.db.ExecContext(ctx, decreaseLeftValues, arg.RoleLeftValue, arg.RoleLeftValue_2)
	return err
}

const decreaseParentRightValues = `-- name: DecreaseParentRightValues :exec
UPDATE role
SET role_right_value = role_right_value - ?
WHERE role_left_value < ? AND role_right_value > ? AND is_deleted = false
`

type DecreaseParentRightValuesParams struct {
	RoleRightValue   int32
	RoleLeftValue    int32
	RoleRightValue_2 int32
}

func (q *Queries) DecreaseParentRightValues(ctx context.Context, arg DecreaseParentRightValuesParams) error {
	_, err := q.db.ExecContext(ctx, decreaseParentRightValues, arg.RoleRightValue, arg.RoleLeftValue, arg.RoleRightValue_2)
	return err
}

const decreaseRightValues = `-- name: DecreaseRightValues :exec
UPDATE role
SET role_right_value = role_right_value - ?
WHERE role_right_value > ? AND is_deleted = false
`

type DecreaseRightValuesParams struct {
	RoleRightValue   int32
	RoleRightValue_2 int32
}

func (q *Queries) DecreaseRightValues(ctx context.Context, arg DecreaseRightValuesParams) error {
	_, err := q.db.ExecContext(ctx, decreaseRightValues, arg.RoleRightValue, arg.RoleRightValue_2)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
UPDATE ` + "`" + `role` + "`" + `
SET is_deleted = true, update_at = ?
WHERE id = ?
`

type DeleteRoleParams struct {
	UpdateAt time.Time
	ID       string
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRole, arg.UpdateAt, arg.ID)
	return err
}

const getAccountCreated = `-- name: GetAccountCreated :one
SELECT COUNT(id) 
FROM ` + "`" + `role` + "`" + ` 
WHERE created_by = ? AND is_deleted = false
`

func (q *Queries) GetAccountCreated(ctx context.Context, createdBy string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAccountCreated, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllFuncPackageByCreatedBy = `-- name: GetAllFuncPackageByCreatedBy :many
SELECT DISTINCT
    r.id,
    r.code,
    r.role_name,
    r.role_max_number,
    r.role_left_value,
    MAX(l.date_start) as date_start,
    MAX(l.date_end) as date_end,
    r.license_id,
    (
        SELECT GROUP_CONCAT(DISTINCT m.menu_name ORDER BY m.menu_name SEPARATOR ',')
        FROM roles_menu rm
        JOIN menu m ON m.id = rm.menu_id
        WHERE rm.role_id = r.id AND rm.is_deleted = false AND m.is_deleted = false
    ) AS menu_names,
    (
        SELECT GROUP_CONCAT(DISTINCT a.id ORDER BY a.id SEPARATOR ',')
        FROM role_account ra
        JOIN account a ON a.id = ra.account_id
        WHERE ra.role_id = r.id AND ra.is_deleted = false AND a.is_deleted = false
    ) AS account_ids,
    (
        SELECT GROUP_CONCAT(DISTINCT a.name ORDER BY a.id SEPARATOR ',')
        FROM role_account ra
        JOIN account a ON a.id = ra.account_id
        WHERE ra.role_id = r.id AND ra.is_deleted = false AND a.is_deleted = false
    ) AS account_names,
    -- ĐÃ SỬA: Bỏ DISTINCT khỏi account_statuses
    (
        SELECT GROUP_CONCAT(COALESCE(a.status, '') ORDER BY a.id SEPARATOR ',')
        FROM role_account ra
        JOIN account a ON a.id = ra.account_id
        WHERE ra.role_id = r.id AND ra.is_deleted = false AND a.is_deleted = false
    ) AS account_statuses,
    (
        SELECT COUNT(DISTINCT ra.account_id)
        FROM role_account ra
        WHERE ra.role_id = r.id AND ra.is_deleted = false
    ) AS account_count
FROM role r
LEFT JOIN license l ON r.id = l.role_id AND l.is_deleted = false
WHERE r.is_deleted = false
  AND r.created_by = ?
  AND (
    ? IS NULL OR ? = '' OR
    r.code LIKE CONCAT('%', ?, '%') OR 
    r.role_name LIKE CONCAT('%', ?, '%') OR 
    EXISTS (
        SELECT 1 FROM role_account ra
        JOIN account a ON a.id = ra.account_id
        WHERE ra.role_id = r.id AND ra.is_deleted = false AND a.is_deleted = false
        AND (
            a.username LIKE CONCAT('%', ?, '%') OR
            a.name LIKE CONCAT('%', ?, '%')
        )
    ) OR
    EXISTS (
        SELECT 1 FROM roles_menu rm
        JOIN menu m ON m.id = rm.menu_id
        WHERE rm.role_id = r.id AND rm.is_deleted = false AND m.is_deleted = false
        AND m.menu_name LIKE CONCAT('%', ?, '%')
    )
  )
GROUP BY r.id, r.code, r.role_name, r.role_max_number, r.role_left_value, r.license_id
ORDER BY r.role_left_value DESC
LIMIT ? OFFSET ?
`

type GetAllFuncPackageByCreatedByParams struct {
	CreatedBy string
	Column2   interface{}
	Column3   interface{}
	CONCAT    interface{}
	CONCAT_2  interface{}
	CONCAT_3  interface{}
	CONCAT_4  interface{}
	CONCAT_5  interface{}
	Limit     int32
	Offset    int32
}

type GetAllFuncPackageByCreatedByRow struct {
	ID              string
	Code            string
	RoleName        string
	RoleMaxNumber   int32
	RoleLeftValue   int32
	DateStart       interface{}
	DateEnd         interface{}
	LicenseID       string
	MenuNames       sql.NullString
	AccountIds      sql.NullString
	AccountNames    sql.NullString
	AccountStatuses sql.NullString
	AccountCount    int64
}

func (q *Queries) GetAllFuncPackageByCreatedBy(ctx context.Context, arg GetAllFuncPackageByCreatedByParams) ([]GetAllFuncPackageByCreatedByRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFuncPackageByCreatedBy,
		arg.CreatedBy,
		arg.Column2,
		arg.Column3,
		arg.CONCAT,
		arg.CONCAT_2,
		arg.CONCAT_3,
		arg.CONCAT_4,
		arg.CONCAT_5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFuncPackageByCreatedByRow
	for rows.Next() {
		var i GetAllFuncPackageByCreatedByRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.RoleName,
			&i.RoleMaxNumber,
			&i.RoleLeftValue,
			&i.DateStart,
			&i.DateEnd,
			&i.LicenseID,
			&i.MenuNames,
			&i.AccountIds,
			&i.AccountNames,
			&i.AccountStatuses,
			&i.AccountCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFuncPackageSelectByCreatedBy = `-- name: GetAllFuncPackageSelectByCreatedBy :many
SELECT 
    r.id, 
    r.role_name, 
    MAX(l.date_end) AS dateend
FROM role r
JOIN roles_menu rm ON r.id = rm.role_id
JOIN license l ON l.role_id = r.id
WHERE r.created_by = ?
  AND r.is_deleted = false
GROUP BY r.id, r.role_name
`

type GetAllFuncPackageSelectByCreatedByRow struct {
	ID       string
	RoleName string
	Dateend  interface{}
}

func (q *Queries) GetAllFuncPackageSelectByCreatedBy(ctx context.Context, createdBy string) ([]GetAllFuncPackageSelectByCreatedByRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFuncPackageSelectByCreatedBy, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFuncPackageSelectByCreatedByRow
	for rows.Next() {
		var i GetAllFuncPackageSelectByCreatedByRow
		if err := rows.Scan(&i.ID, &i.RoleName, &i.Dateend); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT a.id,a.name, r.role_name, m.menu_group_name,rm.list_method as Method FROM account a
JOIN role_account ra ON ra.account_id = a.id
JOIN role r ON r.id = ra.role_id
JOIN roles_menu rm ON rm.role_id = r.id
JOIN menu m ON m.id = rm.menu_id
WHERE a.is_deleted = false AND r.is_deleted = false AND m.is_deleted = false
`

type GetAllPermissionsRow struct {
	ID            string
	Name          string
	RoleName      string
	MenuGroupName string
	Method        json.RawMessage
}

func (q *Queries) GetAllPermissions(ctx context.Context) ([]GetAllPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPermissionsRow
	for rows.Next() {
		var i GetAllPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleName,
			&i.MenuGroupName,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPermissionsByAccountId = `-- name: GetAllPermissionsByAccountId :many
SELECT a.id,a.name, r.role_name, m.menu_group_name,rm.list_method as Method FROM account a
JOIN role_account ra ON ra.account_id = a.id
JOIN role r ON r.id = ra.role_id
JOIN roles_menu rm ON rm.role_id = r.id
JOIN menu m ON m.id = rm.menu_id
WHERE a.is_deleted = false AND r.is_deleted = false AND m.is_deleted = false AND a.id = ?
`

type GetAllPermissionsByAccountIdRow struct {
	ID            string
	Name          string
	RoleName      string
	MenuGroupName string
	Method        json.RawMessage
}

func (q *Queries) GetAllPermissionsByAccountId(ctx context.Context, id string) ([]GetAllPermissionsByAccountIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPermissionsByAccountId, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPermissionsByAccountIdRow
	for rows.Next() {
		var i GetAllPermissionsByAccountIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleName,
			&i.MenuGroupName,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRole = `-- name: GetAllRole :many
SELECT id, code, role_name, role_left_value, role_right_value, role_max_number, created_by, create_at, update_at
FROM ` + "`" + `role` + "`" + `
WHERE is_deleted = false
ORDER BY role_left_value DESC
LIMIT ? OFFSET ?
`

type GetAllRoleParams struct {
	Limit  int32
	Offset int32
}

type GetAllRoleRow struct {
	ID             string
	Code           string
	RoleName       string
	RoleLeftValue  int32
	RoleRightValue int32
	RoleMaxNumber  int32
	CreatedBy      string
	CreateAt       time.Time
	UpdateAt       time.Time
}

func (q *Queries) GetAllRole(ctx context.Context, arg GetAllRoleParams) ([]GetAllRoleRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllRole, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRoleRow
	for rows.Next() {
		var i GetAllRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.RoleName,
			&i.RoleLeftValue,
			&i.RoleRightValue,
			&i.RoleMaxNumber,
			&i.CreatedBy,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChildRolesByParentId = `-- name: GetChildRolesByParentId :many
SELECT id, code, role_name, role_left_value, role_right_value, role_max_number, created_by, create_at, update_at
FROM ` + "`" + `role` + "`" + `
WHERE created_by = ? AND is_deleted = false
ORDER BY role_left_value ASC
`

type GetChildRolesByParentIdRow struct {
	ID             string
	Code           string
	RoleName       string
	RoleLeftValue  int32
	RoleRightValue int32
	RoleMaxNumber  int32
	CreatedBy      string
	CreateAt       time.Time
	UpdateAt       time.Time
}

func (q *Queries) GetChildRolesByParentId(ctx context.Context, createdBy string) ([]GetChildRolesByParentIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getChildRolesByParentId, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChildRolesByParentIdRow
	for rows.Next() {
		var i GetChildRolesByParentIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.RoleName,
			&i.RoleLeftValue,
			&i.RoleRightValue,
			&i.RoleMaxNumber,
			&i.CreatedBy,
			&i.CreateAt,
			&i.UpdateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxRightValue = `-- name: GetMaxRightValue :one
SELECT COALESCE(MAX(role_right_value), 0) as max_right_value
FROM ` + "`" + `role` + "`" + `
WHERE is_deleted = false
`

func (q *Queries) GetMaxRightValue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxRightValue)
	var max_right_value interface{}
	err := row.Scan(&max_right_value)
	return max_right_value, err
}

const getParentRoleInfo = `-- name: GetParentRoleInfo :one
SELECT role_left_value, role_right_value
FROM ` + "`" + `role` + "`" + `
WHERE id = ? AND is_deleted = false
`

type GetParentRoleInfoRow struct {
	RoleLeftValue  int32
	RoleRightValue int32
}

func (q *Queries) GetParentRoleInfo(ctx context.Context, id string) (GetParentRoleInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getParentRoleInfo, id)
	var i GetParentRoleInfoRow
	err := row.Scan(&i.RoleLeftValue, &i.RoleRightValue)
	return i, err
}

const getRoleById = `-- name: GetRoleById :one
SELECT id, code, role_name,role_left_value,role_right_value,role_max_number,created_by,create_at,update_at
FROM ` + "`" + `role` + "`" + `
WHERE id = ? AND is_deleted = false
`

type GetRoleByIdRow struct {
	ID             string
	Code           string
	RoleName       string
	RoleLeftValue  int32
	RoleRightValue int32
	RoleMaxNumber  int32
	CreatedBy      string
	CreateAt       time.Time
	UpdateAt       time.Time
}

func (q *Queries) GetRoleById(ctx context.Context, id string) (GetRoleByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleById, id)
	var i GetRoleByIdRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.RoleName,
		&i.RoleLeftValue,
		&i.RoleRightValue,
		&i.RoleMaxNumber,
		&i.CreatedBy,
		&i.CreateAt,
		&i.UpdateAt,
	)
	return i, err
}

const getTotalAccounts = `-- name: GetTotalAccounts :one
SELECT COALESCE(CAST(SUM(role_max_number) AS SIGNED), 0) AS MaxNumberAccount
FROM ` + "`" + `role` + "`" + `
WHERE (created_by = ? OR ? IS NULL OR ? = '')
    AND is_deleted = false
`

type GetTotalAccountsParams struct {
	CreatedBy string
	Column2   interface{}
	Column3   interface{}
}

func (q *Queries) GetTotalAccounts(ctx context.Context, arg GetTotalAccountsParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getTotalAccounts, arg.CreatedBy, arg.Column2, arg.Column3)
	var maxnumberaccount interface{}
	err := row.Scan(&maxnumberaccount)
	return maxnumberaccount, err
}

const getTotalRoles = `-- name: GetTotalRoles :one
SELECT COUNT(*) FROM ` + "`" + `role` + "`" + ` WHERE is_deleted = false
`

func (q *Queries) GetTotalRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteRolesByRange = `-- name: SoftDeleteRolesByRange :exec
UPDATE ` + "`" + `role` + "`" + `
SET is_deleted = true, update_at = ?
WHERE role_left_value >= ? AND role_right_value <= ? AND is_deleted = false
`

type SoftDeleteRolesByRangeParams struct {
	UpdateAt       time.Time
	RoleLeftValue  int32
	RoleRightValue int32
}

func (q *Queries) SoftDeleteRolesByRange(ctx context.Context, arg SoftDeleteRolesByRangeParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteRolesByRange, arg.UpdateAt, arg.RoleLeftValue, arg.RoleRightValue)
	return err
}

const updateLeftValuesForInsert = `-- name: UpdateLeftValuesForInsert :exec
UPDATE ` + "`" + `role` + "`" + `
SET role_left_value = role_left_value + 2
WHERE role_left_value > ? AND is_deleted = false
`

func (q *Queries) UpdateLeftValuesForInsert(ctx context.Context, roleLeftValue int32) error {
	_, err := q.db.ExecContext(ctx, updateLeftValuesForInsert, roleLeftValue)
	return err
}

const updateLicenseByRoleId = `-- name: UpdateLicenseByRoleId :exec
UPDATE ` + "`" + `role` + "`" + `
SET license_id = ?
WHERE id = ? AND is_deleted = false
`

type UpdateLicenseByRoleIdParams struct {
	LicenseID string
	ID        string
}

func (q *Queries) UpdateLicenseByRoleId(ctx context.Context, arg UpdateLicenseByRoleIdParams) error {
	_, err := q.db.ExecContext(ctx, updateLicenseByRoleId, arg.LicenseID, arg.ID)
	return err
}

const updateRightValuesForInsert = `-- name: UpdateRightValuesForInsert :exec
UPDATE ` + "`" + `role` + "`" + `
SET role_right_value = role_right_value + 2
WHERE role_right_value >= ? AND is_deleted = false
`

func (q *Queries) UpdateRightValuesForInsert(ctx context.Context, roleRightValue int32) error {
	_, err := q.db.ExecContext(ctx, updateRightValuesForInsert, roleRightValue)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE ` + "`" + `role` + "`" + `
SET code = ?, role_name = ?,role_left_value = ?,role_right_value = ?,role_max_number = ?,created_by = ?,update_at = NOW()
WHERE id = ?
`

type UpdateRoleParams struct {
	Code           string
	RoleName       string
	RoleLeftValue  int32
	RoleRightValue int32
	RoleMaxNumber  int32
	CreatedBy      string
	ID             string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole,
		arg.Code,
		arg.RoleName,
		arg.RoleLeftValue,
		arg.RoleRightValue,
		arg.RoleMaxNumber,
		arg.CreatedBy,
		arg.ID,
	)
	return err
}
