// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 0005_rolesMenu.sql

package database

import (
	"context"
	"encoding/json"
	"time"
)

const createRolesMenu = `-- name: CreateRolesMenu :exec
INSERT INTO ` + "`" + `roles_menu` + "`" + ` (id, menu_id, role_id, list_method, is_deleted, create_at, update_at)
VALUES (?, ?, ?, ?, false, NOW(), NOW())
`

type CreateRolesMenuParams struct {
	ID         string
	MenuID     string
	RoleID     string
	ListMethod json.RawMessage
}

func (q *Queries) CreateRolesMenu(ctx context.Context, arg CreateRolesMenuParams) error {
	_, err := q.db.ExecContext(ctx, createRolesMenu,
		arg.ID,
		arg.MenuID,
		arg.RoleID,
		arg.ListMethod,
	)
	return err
}

const deleteRolesMenu = `-- name: DeleteRolesMenu :exec
UPDATE ` + "`" + `roles_menu` + "`" + `
SET is_deleted = true, update_at = ?
WHERE id = ?
`

type DeleteRolesMenuParams struct {
	UpdateAt time.Time
	ID       string
}

func (q *Queries) DeleteRolesMenu(ctx context.Context, arg DeleteRolesMenuParams) error {
	_, err := q.db.ExecContext(ctx, deleteRolesMenu, arg.UpdateAt, arg.ID)
	return err
}

const getRoleMenuByRoleId = `-- name: GetRoleMenuByRoleId :many
SELECT 
    m.id, 
    m.menu_name, 
    m.menu_url, 
    m.menu_icon, 
    rm.menu_id,
    rm.role_id,
    m.menu_group_name, 
    r.code, 
    r.role_name, 
    rm.list_method 
FROM roles_menu rm
JOIN menu m ON m.id = rm.menu_id AND m.is_deleted = FALSE
JOIN role r ON r.id = rm.role_id AND r.is_deleted = FALSE
WHERE r.id = ? AND r.role_name LIKE ?
`

type GetRoleMenuByRoleIdParams struct {
	ID       string
	RoleName string
}

type GetRoleMenuByRoleIdRow struct {
	ID            string
	MenuName      string
	MenuUrl       string
	MenuIcon      string
	MenuID        string
	RoleID        string
	MenuGroupName string
	Code          string
	RoleName      string
	ListMethod    json.RawMessage
}

func (q *Queries) GetRoleMenuByRoleId(ctx context.Context, arg GetRoleMenuByRoleIdParams) ([]GetRoleMenuByRoleIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRoleMenuByRoleId, arg.ID, arg.RoleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleMenuByRoleIdRow
	for rows.Next() {
		var i GetRoleMenuByRoleIdRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuName,
			&i.MenuUrl,
			&i.MenuIcon,
			&i.MenuID,
			&i.RoleID,
			&i.MenuGroupName,
			&i.Code,
			&i.RoleName,
			&i.ListMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesMenuByID = `-- name: GetRolesMenuByID :many
SELECT id, menu_id, role_id, list_method
FROM ` + "`" + `roles_menu` + "`" + `
WHERE id = ? AND is_deleted = false
`

type GetRolesMenuByIDRow struct {
	ID         string
	MenuID     string
	RoleID     string
	ListMethod json.RawMessage
}

func (q *Queries) GetRolesMenuByID(ctx context.Context, id string) ([]GetRolesMenuByIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getRolesMenuByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesMenuByIDRow
	for rows.Next() {
		var i GetRolesMenuByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.RoleID,
			&i.ListMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesMenuByRoleId = `-- name: GetRolesMenuByRoleId :many
SELECT id, menu_id, role_id, list_method
FROM ` + "`" + `roles_menu` + "`" + `
WHERE role_id = ? AND is_deleted = false
`

type GetRolesMenuByRoleIdRow struct {
	ID         string
	MenuID     string
	RoleID     string
	ListMethod json.RawMessage
}

func (q *Queries) GetRolesMenuByRoleId(ctx context.Context, roleID string) ([]GetRolesMenuByRoleIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getRolesMenuByRoleId, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesMenuByRoleIdRow
	for rows.Next() {
		var i GetRolesMenuByRoleIdRow
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.RoleID,
			&i.ListMethod,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRolesMenu = `-- name: UpdateRolesMenu :exec
UPDATE ` + "`" + `roles_menu` + "`" + `
SET menu_id = ?, role_id = ?, list_method = ?
WHERE id = ?
`

type UpdateRolesMenuParams struct {
	MenuID     string
	RoleID     string
	ListMethod json.RawMessage
	ID         string
}

func (q *Queries) UpdateRolesMenu(ctx context.Context, arg UpdateRolesMenuParams) error {
	_, err := q.db.ExecContext(ctx, updateRolesMenu,
		arg.MenuID,
		arg.RoleID,
		arg.ListMethod,
		arg.ID,
	)
	return err
}
