// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 0016_payment.sql

package database

import (
	"context"
	"database/sql"
)

const addPayment = `-- name: AddPayment :execresult
INSERT INTO ` + "`" + `payment` + "`" + ` (
    id,
    name,
    is_deleted,
    created_at,
    updated_at
)
VALUES(?,?,false,NOW(),NOW())
`

type AddPaymentParams struct {
	ID   string
	Name string
}

func (q *Queries) AddPayment(ctx context.Context, arg AddPaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addPayment, arg.ID, arg.Name)
}
