// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: 0018_transaction_history.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const addTransactionHistory = `-- name: AddTransactionHistory :execresult
INSERT INTO ` + "`" + `transaction_history` + "`" + ` (
    id,
    number_plate,
    time_in,
    time_out,
    spot_number,
    status,
    is_deleted,
    created_at,
    updated_at
)
VALUES(?,?,?,?,?,?,false,NOW(),NOW())
`

type AddTransactionHistoryParams struct {
	ID          string
	NumberPlate string
	TimeIn      time.Time
	TimeOut     time.Time
	SpotNumber  int32
	Status      bool
}

func (q *Queries) AddTransactionHistory(ctx context.Context, arg AddTransactionHistoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addTransactionHistory,
		arg.ID,
		arg.NumberPlate,
		arg.TimeIn,
		arg.TimeOut,
		arg.SpotNumber,
		arg.Status,
	)
}
